### ISSUE TITLE
Lab 1: filtering genes

### ISSUE THREAD

**Issue by tmms1** [statOmics/singleCellCourse#3]
Dear Jeroen 

First of all, thank you for the interesting lab session on Wednesday.

I am posting my question here, because I think the answer can be useful for other participants. 

During the lab session we filtered out genes that were expressed only in "a few cells". You mentioned that is always crucial to look at what you are filtering out. For filtering out cells, you showed examples of which plot are insightful. Which plots are insightful when filtering out genes? 

--
With kind regards
Tim

**Comment by koenvandenberge** [comment]
Hi @tmms1,

Thanks for your question.
I think several plots could be useful here. Below I give a few suggestions from the top of my head, but feel free to explore deeper and share the results ;-).

 - The number/fraction of cells in which expression is detected.
 - The total gene expression output per gene.
 - Similar as above, but using the expression fraction (gene expression divided by sequencing depth).
 
In particular visualizations like `plot(sort(rowSums(assays(sce)$counts > 0), decreasing=TRUE), log="y")` I believe are useful.
